import { useEffect, useState } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { apiPost, safeGet } from '../lib/api'
import {
  ArrowLeft,
  MapPin,
  Calendar,
  Clock,
  Bike,
  CircleCheck as CheckCircle,
  Circle,
  Truck,
  Phone,
  Star,
  MessageSquare,
  RefreshCw,
  Wrench,
} from 'lucide-react'

interface VehicleInfo {
  nickname?: string | null
  displayName?: string | null
  display_name?: string | null
  registrationNo?: string | null
  registration_number?: string | null
  registration_no?: string | null
  brand?: string | null
  brand_name?: string | null
  model_name?: string | null
  oem?: { name?: string | null } | null
  model?: { name?: string | null } | null
  vehicle_oems?: { name?: string | null } | null
  vehicle_models?: { name?: string | null } | null
}

interface CenterInfo {
  id?: string
  name?: string | null
  address?: string | null
  city?: string | null
  phone?: string | null
  rating?: number | null
}

interface WipEvent {
  id: string
  stage: string
  remarks?: string | null
  photoUrl?: string | null
  createdAt?: string | null
  created_at?: string | null
}

interface JobCardTracking {
  id?: string
  number?: string | null
  trackingId?: string | null
  bikeai_tracking_id?: string | null
  tracking_id?: string | null
  status?: string | null
  workflowStage?: string | null
  workflow_stage?: string | null
  advisorName?: string | null
  advisor_name?: string | null
  technicianName?: string | null
  technician_name?: string | null
  bayNumber?: number | null
  bay_number?: number | null
  estimatedReady?: string | null
  estimated_ready?: string | null
  complaint?: string | null
  wipEvents?: WipEvent[]
  wip_events?: WipEvent[]
}

interface Booking {
  id: string
  serviceType?: string | null
  service_type?: string | null
  service_category?: string | null
  scheduledAt?: string | null
  scheduled_at?: string | null
  scheduled_date?: string | null
  scheduled_time?: string | null
  status: string
  current_stage?: string | null
  pickup_required?: boolean
  pickup_address?: string | null
  drop_required?: boolean
  notes?: string | null
  estimated_cost?: number
  final_cost?: number
  otp_verified?: boolean
  tracking_enabled?: boolean
  created_at?: string
  completed_at?: string
  service_center?: CenterInfo | null
  service_centers?: CenterInfo | null
  dealer?: CenterInfo | null
  vehicle?: VehicleInfo | null
  customer_vehicles?: VehicleInfo | null
  jobCard?: JobCardTracking | null
  job_card?: JobCardTracking | null
}

type WorkOrderStage =
  | 'TRACKING_CREATED'
  | 'INSPECTION_COMPLETED'
  | 'ESTIMATE_CREATED'
  | 'APPROVAL_PENDING'
  | 'APPROVED'
  | 'WORK_ALLOCATED'
  | 'PARTS_ISSUED'
  | 'WORK_IN_PROGRESS'
  | 'WORK_COMPLETED'
  | 'QC_PASS'
  | 'WASHING'
  | 'WASH_COMPLETED'
  | 'READY_FOR_BILLING'
  | 'INVOICE_GENERATED'
  | 'READY_FOR_DELIVERY'
  | 'PAYMENT_RECEIVED'
  | 'DELIVERED'
  | 'FEEDBACK_RECEIVED'

const JOBCARD_STAGES: Array<{ id: WorkOrderStage; label: string; desc: string }> = [
  { id: 'TRACKING_CREATED', label: 'Tracking Created', desc: 'BikeAI tracking opened' },
  { id: 'INSPECTION_COMPLETED', label: 'Inspection Completed', desc: 'Vehicle inspection completed' },
  { id: 'ESTIMATE_CREATED', label: 'Estimate Created', desc: 'Estimate prepared by workshop' },
  { id: 'APPROVAL_PENDING', label: 'Approval Pending', desc: 'Waiting for customer/workshop approval' },
  { id: 'APPROVED', label: 'Approved', desc: 'Approval completed' },
  { id: 'WORK_ALLOCATED', label: 'Work Allocated', desc: 'Work assigned inside workshop' },
  { id: 'PARTS_ISSUED', label: 'Spares Issued', desc: 'Required spares issued' },
  { id: 'WORK_IN_PROGRESS', label: 'Work In Progress', desc: 'Service work is underway' },
  { id: 'WORK_COMPLETED', label: 'Work Completed', desc: 'Service work completed' },
  { id: 'QC_PASS', label: 'QC Completed', desc: 'Quality check completed' },
  { id: 'WASHING', label: 'Washing', desc: 'Vehicle sent to washing' },
  { id: 'WASH_COMPLETED', label: 'Washing Done', desc: 'Vehicle washing completed' },
  { id: 'READY_FOR_BILLING', label: 'Ready for Billing', desc: 'Billing can be prepared' },
  { id: 'INVOICE_GENERATED', label: 'Invoice Generated', desc: 'Invoice generated by workshop' },
  { id: 'READY_FOR_DELIVERY', label: 'Ready for Delivery', desc: 'Vehicle is ready for pickup/delivery' },
  { id: 'PAYMENT_RECEIVED', label: 'Payment Received', desc: 'Payment received' },
  { id: 'DELIVERED', label: 'Delivered', desc: 'Vehicle delivered' },
  { id: 'FEEDBACK_RECEIVED', label: 'Feedback Received', desc: 'Feedback received' },
]

const STAGE_ALIASES: Record<string, WorkOrderStage> = {
  SPARES_ISSUED: 'PARTS_ISSUED',
  SERVICE_FINISHED: 'READY_FOR_DELIVERY',
  GATE_PASS_GENERATED: 'DELIVERED',
}

const LEGACY_STAGES = [
  { id: 'booking_confirmed', label: 'Booking Confirmed', desc: 'Your booking has been received' },
  { id: 'pickup_scheduled', label: 'Pickup Scheduled', desc: 'Our rider is on the way' },
  { id: 'vehicle_received', label: 'Vehicle Received', desc: 'Workshop has your vehicle' },
  { id: 'diagnosis', label: 'Diagnosis', desc: 'Technician is inspecting your vehicle' },
  { id: 'work_in_progress', label: 'Work In Progress', desc: 'Service is underway' },
  { id: 'quality_check', label: 'Quality Check', desc: 'Final inspection in progress' },
  { id: 'ready_for_delivery', label: 'Ready for Delivery', desc: 'Your vehicle is ready!' },
  { id: 'completed', label: 'Completed', desc: 'Service completed successfully' },
]

const STATUS_CONFIG: Record<string, { label: string; color: string; bg: string }> = {
  pending: { label: 'Pending', color: '#d97706', bg: '#fffbeb' },
  confirmed: { label: 'Confirmed', color: '#2563eb', bg: '#eff6ff' },
  in_progress: { label: 'In Progress', color: '#7c3aed', bg: '#faf5ff' },
  completed: { label: 'Completed', color: '#16a34a', bg: '#f0fdf4' },
  cancelled: { label: 'Cancelled', color: '#dc2626', bg: '#fef2f2' },
}

function normalizeStage(value?: string | null): WorkOrderStage {
  const raw = String(value || 'TRACKING_CREATED').toUpperCase()
  return STAGE_ALIASES[raw] || (JOBCARD_STAGES.some(stage => stage.id === raw) ? raw as WorkOrderStage : 'TRACKING_CREATED')
}

function label(value?: string | null) {
  if (!value) return '-'
  return value.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
}

function formatServiceLabel(value?: string | null) {
  if (!value) return 'Service'

  const labels: Record<string, string> = {
    general_service: 'General Service',
    minor_repairs: 'Minor Repairs',
    major_service: 'Major Service',
    free_service: 'Free Service',
    accident_repair: 'Accident Repair',
    breakdown_help: 'Breakdown Help',
    ev_diagnostics: 'EV Diagnostics',
    tyre_battery: 'Tyre & Battery',
    rsa_support: 'RSA Support',
    paid_service: 'Paid Service',
    walk_in: 'Walk In',
  }

  return labels[value] || value.replace(/_/g, ' ').replace(/\b\w/g, char => char.toUpperCase())
}

function getServiceValue(booking: Booking) {
  return booking.service_type || booking.serviceType || booking.service_category || ''
}

function getScheduledDate(booking: Booking) {
  return booking.scheduled_date || booking.scheduledAt || booking.scheduled_at || ''
}

function getScheduledTime(booking: Booking) {
  if (booking.scheduled_time) return booking.scheduled_time
  const raw = booking.scheduledAt || booking.scheduled_at
  if (!raw) return ''
  const date = new Date(raw)
  if (Number.isNaN(date.getTime())) return ''
  return date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: false })
}

function formatFullDate(value?: string | null) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '-'
  return date.toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })
}

function formatDateTime(value?: string | null) {
  if (!value) return '-'
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return '-'
  return date.toLocaleString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })
}

function getCenter(booking: Booking) {
  return booking.service_center || booking.service_centers || booking.dealer || null
}

function getVehicle(booking: Booking) {
  return booking.vehicle || booking.customer_vehicles || null
}

function getVehicleLabel(vehicle?: VehicleInfo | null) {
  if (!vehicle) return '-'
  const brand = vehicle.brand || vehicle.brand_name || vehicle.oem?.name || vehicle.vehicle_oems?.name || ''
  const model = vehicle.model_name || vehicle.model?.name || vehicle.vehicle_models?.name || ''
  const name = vehicle.nickname || vehicle.displayName || vehicle.display_name || `${brand} ${model}`.trim() || 'My Vehicle'
  const reg = vehicle.registrationNo || vehicle.registration_number || vehicle.registration_no || ''
  return reg ? `${name} · ${reg}` : name
}

function getJobCard(booking: Booking) {
  return booking.jobCard || booking.job_card || null
}

function getJobCardEvents(jobCard?: JobCardTracking | null) {
  return jobCard?.wipEvents || jobCard?.wip_events || []
}

function getCurrentJobStage(jobCard?: JobCardTracking | null) {
  return normalizeStage(jobCard?.workflowStage || jobCard?.workflow_stage || jobCard?.status || 'TRACKING_CREATED')
}

export default function BookingDetailPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()

  const [booking, setBooking] = useState<Booking | null>(null)
  const [loading, setLoading] = useState(true)
  const [rating, setRating] = useState(0)
  const [reviewText, setReviewText] = useState('')
  const [reviewSubmitted, setReviewSubmitted] = useState(false)

  const load = async () => {
    if (!id) return
    setLoading(true)
    const data = await safeGet<Booking | null>(`/api/bookings/${encodeURIComponent(id)}`, null)
    if (data) setBooking(data)
    setLoading(false)
  }

  useEffect(() => {
    load()
  }, [id])

  const handleCancel = async () => {
    if (!booking || !confirm('Cancel this booking?')) return
    try {
      await apiPost(`/api/bookings/${booking.id}/cancel`, { cancelled_at: new Date().toISOString() })
    } catch {
      // Still update UI.
    }
    setBooking(prev => prev ? { ...prev, status: 'cancelled' } : prev)
  }

  const handleReview = async () => {
    if (!booking || rating === 0) return
    try {
      const center = getCenter(booking)
      await apiPost('/api/reviews', {
        booking_id: booking.id,
        service_center_id: center?.id,
        rating,
        review_text: reviewText,
      })
    } catch {
      // Non-fatal.
    }
    setReviewSubmitted(true)
  }

  if (loading) return <div style={s.loading}>Loading booking...</div>
  if (!booking) return <div style={s.loading}>Booking not found.</div>

  const sc = STATUS_CONFIG[booking.status] || STATUS_CONFIG.pending
  const center = getCenter(booking)
  const vehicle = getVehicle(booking)
  const cost = Number(booking.final_cost || booking.estimated_cost || 0)
  const serviceLabel = formatServiceLabel(getServiceValue(booking))
  const jobCard = getJobCard(booking)
  const currentStage = getCurrentJobStage(jobCard)
  const currentStageIndex = JOBCARD_STAGES.findIndex(stage => stage.id === currentStage)
  const jobCardEvents = getJobCardEvents(jobCard)
  const trackingId = jobCard?.number || jobCard?.trackingId || jobCard?.bikeai_tracking_id || jobCard?.tracking_id || ''

  return (
    <div style={s.root}>
      <div style={s.header}>
        <button style={s.backBtn} onClick={() => navigate(-1)}><ArrowLeft size={18} /></button>
        <div style={s.headerInfo}>
          <h1 style={s.title}>{serviceLabel}</h1>
          <p style={s.bookingId}>#{booking.id.slice(0, 8).toUpperCase()}</p>
        </div>
        <span style={{ ...s.badge, color: sc.color, background: sc.bg }}>{sc.label}</span>
      </div>

      {jobCard && booking.status !== 'cancelled' ? (
        <div style={s.trackCard}>
          <div style={s.trackHead}>
            <div>
              <h2 style={s.trackTitle}>Live Service Tracking</h2>
              <p style={s.trackId}>BikeAI Tracking ID: {trackingId || '-'}</p>
            </div>
            <button style={s.refreshBtn} onClick={load}><RefreshCw size={14} /> Refresh</button>
          </div>

          <div style={s.currentStatusBox}>
            <span>CURRENT STATUS</span>
            <strong>{label(currentStage)}</strong>
          </div>

          <div style={s.trackMetaGrid}>
            <span>Advisor: <strong>{jobCard.advisorName || jobCard.advisor_name || '-'}</strong></span>
            <span>Technician: <strong>{jobCard.technicianName || jobCard.technician_name || '-'}</strong></span>
            <span>Ramp / Bay: <strong>{jobCard.bayNumber || jobCard.bay_number ? `Bay ${jobCard.bayNumber || jobCard.bay_number}` : '-'}</strong></span>
            <span>Ready Time: <strong>{formatDateTime(jobCard.estimatedReady || jobCard.estimated_ready)}</strong></span>
          </div>

          <div style={s.timeline}>
            {JOBCARD_STAGES.map((stage, i) => {
              const done = currentStageIndex >= 0 && i <= currentStageIndex
              const active = currentStageIndex >= 0 && i === currentStageIndex
              const event = jobCardEvents.find(item => normalizeStage(item.stage) === stage.id)

              return (
                <div key={stage.id} style={s.timelineItem}>
                  <div style={s.timelineDotCol}>
                    <div style={{
                      ...s.dot,
                      background: done ? '#f5a623' : '#e2e6f0',
                      border: active ? '3px solid #f5a623' : 'none',
                      boxShadow: active ? '0 0 0 4px rgba(245,166,35,0.2)' : 'none',
                    }}>
                      {done && !active && <CheckCircle size={14} color="white" />}
                      {active && <div style={s.activePulse} />}
                      {!done && <Circle size={14} color="#d1d5db" />}
                    </div>
                    {i < JOBCARD_STAGES.length - 1 && <div style={{ ...s.connector, background: done ? '#f5a623' : '#e2e6f0' }} />}
                  </div>
                  <div style={s.timelineContent}>
                    <span style={{ ...s.stageLabel, color: done ? '#0f2044' : '#9aa3b8', fontWeight: active ? '800' : '600' }}>{stage.label}</span>
                    {(active || event) && <span style={s.stageDesc}>{event?.remarks || stage.desc}</span>}
                    {event && <small style={s.stageTime}>{formatDateTime(event.createdAt || event.created_at)}</small>}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      ) : booking.tracking_enabled && booking.status !== 'cancelled' ? (
        <div style={s.trackCard}>
          <h2 style={s.trackTitle}>Live Tracking</h2>
          <div style={s.timeline}>
            {LEGACY_STAGES.map((stage, i) => {
              const stageIndex = LEGACY_STAGES.findIndex(item => item.id === booking.current_stage)
              const done = stageIndex >= 0 && i <= stageIndex
              const active = stageIndex >= 0 && i === stageIndex
              return (
                <div key={stage.id} style={s.timelineItem}>
                  <div style={s.timelineDotCol}>
                    <div style={{ ...s.dot, background: done ? '#f5a623' : '#e2e6f0', border: active ? '3px solid #f5a623' : 'none', boxShadow: active ? '0 0 0 4px rgba(245,166,35,0.2)' : 'none' }}>
                      {done && !active && <CheckCircle size={14} color="white" />}
                      {active && <div style={s.activePulse} />}
                      {!done && <Circle size={14} color="#d1d5db" />}
                    </div>
                    {i < LEGACY_STAGES.length - 1 && <div style={{ ...s.connector, background: done ? '#f5a623' : '#e2e6f0' }} />}
                  </div>
                  <div style={s.timelineContent}>
                    <span style={{ ...s.stageLabel, color: done ? '#0f2044' : '#9aa3b8', fontWeight: active ? '700' : '500' }}>{stage.label}</span>
                    {active && <span style={s.stageDesc}>{stage.desc}</span>}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      ) : null}

      <div style={s.grid}>
        <div style={s.card}>
          <h2 style={s.cardTitle}>Booking Details</h2>
          <div style={s.details}>
            <DetailRow icon={<Calendar size={15} color="#f5a623" />} label="Date" value={formatFullDate(getScheduledDate(booking))} />
            <DetailRow icon={<Clock size={15} color="#f5a623" />} label="Time" value={getScheduledTime(booking) || '-'} />
            <DetailRow icon={<span style={{ fontSize: '15px', color: '#f5a623' }}>🔧</span>} label="Service" value={serviceLabel} />
            {vehicle && <DetailRow icon={<Bike size={15} color="#f5a623" />} label="Vehicle" value={getVehicleLabel(vehicle)} />}
            {jobCard?.complaint && <DetailRow icon={<Wrench size={15} color="#f5a623" />} label="Complaint" value={jobCard.complaint} />}
            {booking.pickup_required && <DetailRow icon={<Truck size={15} color="#f5a623" />} label="Pickup" value={booking.pickup_address || 'Pickup arranged'} />}
            {booking.notes && <DetailRow icon={<MessageSquare size={15} color="#f5a623" />} label="Notes" value={booking.notes} />}
            {cost > 0 && <DetailRow icon={<span style={{ fontSize: '15px' }}>₹</span>} label={Number(booking.final_cost || 0) > 0 ? 'Final Cost' : 'Estimated'} value={`₹${cost.toLocaleString('en-IN')}`} />}
          </div>
        </div>

        {center && (
          <div style={s.card}>
            <h2 style={s.cardTitle}>Service Center</h2>
            <div style={s.centerInfo}>
              <div style={s.centerIconWrap}><MapPin size={24} color="#f5a623" /></div>
              <div>
                <p style={s.centerName}>{center.name || 'Service Center'}</p>
                <p style={s.centerAddr}>{[center.address, center.city].filter(Boolean).join(', ') || '-'}</p>
                {center.phone && <a href={`tel:${center.phone}`} style={s.callBtn}><Phone size={14} /> Call Center</a>}
              </div>
            </div>
          </div>
        )}
      </div>

      {booking.status === 'completed' && !reviewSubmitted && (
        <div style={s.card}>
          <h2 style={s.cardTitle}>Rate Your Experience</h2>
          <div style={{ display: 'flex', gap: '8px', marginBottom: '16px' }}>
            {[1, 2, 3, 4, 5].map(n => (
              <button key={n} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '4px' }} onClick={() => setRating(n)}>
                <Star size={28} fill={n <= rating ? '#f5a623' : 'none'} color={n <= rating ? '#f5a623' : '#d1d5db'} />
              </button>
            ))}
          </div>
          <textarea style={s.reviewInput} value={reviewText} onChange={e => setReviewText(e.target.value)} placeholder="Tell us about your experience..." rows={3} />
          <button style={s.reviewBtn} onClick={handleReview} disabled={rating === 0}>Submit Review</button>
        </div>
      )}

      {reviewSubmitted && (
        <div style={{ ...s.card, background: '#f0fdf4', border: '1px solid #bbf7d0' }}>
          <p style={{ color: '#16a34a', fontWeight: '600', margin: 0 }}>Thank you for your review!</p>
        </div>
      )}

      <div style={s.actions}>
        {['pending', 'confirmed'].includes(booking.status) && <button style={s.cancelBtn} onClick={handleCancel}>Cancel Booking</button>}
        <Link to="/my/book" style={s.rebookBtn}>Book Again</Link>
      </div>
    </div>
  )
}

function DetailRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div style={{ display: 'flex', gap: '12px', paddingBottom: '12px', borderBottom: '1px solid #f0f2f8' }}>
      <div style={{ width: '32px', height: '32px', background: '#fffbeb', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>{icon}</div>
      <div style={{ flex: 1 }}>
        <p style={{ margin: '0 0 2px', fontSize: '11px', color: '#9aa3b8', fontWeight: '500', textTransform: 'uppercase', letterSpacing: '0.04em' }}>{label}</p>
        <p style={{ margin: 0, fontSize: '14px', color: '#0f2044', fontWeight: '600' }}>{value}</p>
      </div>
    </div>
  )
}

const s: Record<string, React.CSSProperties> = {
  root: { display: 'flex', flexDirection: 'column', gap: '20px', maxWidth: '860px' },
  loading: { padding: '40px', textAlign: 'center', color: '#9aa3b8' },
  header: { display: 'flex', alignItems: 'center', gap: '14px' },
  backBtn: { background: '#f5f7fa', border: 'none', borderRadius: '10px', padding: '10px', cursor: 'pointer', display: 'flex', alignItems: 'center' },
  headerInfo: { flex: 1 },
  title: { fontSize: '20px', fontWeight: '800', color: '#0f2044', margin: '0 0 2px' },
  bookingId: { fontSize: '12px', color: '#9aa3b8', margin: 0, fontFamily: 'monospace' },
  badge: { fontSize: '13px', fontWeight: '700', padding: '5px 14px', borderRadius: '20px', flexShrink: 0 },
  trackCard: { background: 'white', borderRadius: '16px', padding: '24px', boxShadow: '0 2px 12px rgba(0,0,0,0.05)' },
  trackHead: { display: 'flex', justifyContent: 'space-between', gap: '12px', alignItems: 'flex-start', marginBottom: '16px' },
  trackTitle: { fontSize: '16px', fontWeight: '700', color: '#0f2044', margin: '0 0 6px' },
  trackId: { margin: 0, fontSize: '12px', color: '#9aa3b8' },
  refreshBtn: { display: 'inline-flex', alignItems: 'center', gap: '6px', background: 'white', color: '#0f2044', border: '1px solid #e2e6f0', borderRadius: '10px', padding: '8px 12px', fontWeight: 700, cursor: 'pointer' },
  currentStatusBox: { border: '1px solid #fcd34d', background: '#fffbeb', borderRadius: '12px', padding: '14px', display: 'grid', gap: '6px', marginBottom: '16px' },
  trackMetaGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '10px', color: '#64748b', fontSize: '13px', marginBottom: '18px' },
  timeline: { display: 'flex', flexDirection: 'column', gap: '0' },
  timelineItem: { display: 'flex', gap: '14px', alignItems: 'flex-start' },
  timelineDotCol: { display: 'flex', flexDirection: 'column', alignItems: 'center', width: '28px', flexShrink: 0 },
  dot: { width: '28px', height: '28px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  activePulse: { width: '10px', height: '10px', background: 'white', borderRadius: '50%' },
  connector: { width: '2px', height: '24px', margin: '2px 0' },
  timelineContent: { paddingBottom: '20px', flex: 1, display: 'flex', flexDirection: 'column', gap: '2px', paddingTop: '4px' },
  stageLabel: { fontSize: '14px' },
  stageDesc: { fontSize: '12px', color: '#9aa3b8' },
  stageTime: { color: '#94a3b8', fontWeight: 600 },
  grid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' },
  card: { background: 'white', borderRadius: '16px', padding: '20px', boxShadow: '0 2px 12px rgba(0,0,0,0.05)' },
  cardTitle: { fontSize: '15px', fontWeight: '700', color: '#0f2044', margin: '0 0 16px' },
  details: { display: 'flex', flexDirection: 'column', gap: '0' },
  centerInfo: { display: 'flex', gap: '14px', alignItems: 'flex-start' },
  centerIconWrap: { width: '44px', height: '44px', background: '#fffbeb', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  centerName: { fontSize: '15px', fontWeight: '700', color: '#0f2044', margin: '0 0 4px' },
  centerAddr: { fontSize: '13px', color: '#9aa3b8', margin: '0 0 10px' },
  callBtn: { display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '7px 16px', background: '#0f2044', color: 'white', borderRadius: '8px', fontSize: '13px', fontWeight: '600', textDecoration: 'none' },
  reviewInput: { width: '100%', padding: '11px 14px', border: '1.5px solid #e2e6f0', borderRadius: '10px', fontSize: '14px', fontFamily: 'inherit', resize: 'vertical', marginBottom: '12px', boxSizing: 'border-box' },
  reviewBtn: { padding: '10px 24px', background: '#f5a623', color: 'white', border: 'none', borderRadius: '10px', fontSize: '14px', fontWeight: '700', cursor: 'pointer' },
  actions: { display: 'flex', gap: '12px' },
  cancelBtn: { padding: '11px 24px', background: '#fef2f2', color: '#dc2626', border: '1px solid #fecaca', borderRadius: '10px', fontSize: '14px', fontWeight: '600', cursor: 'pointer' },
  rebookBtn: { padding: '11px 24px', background: '#0f2044', color: 'white', borderRadius: '10px', fontSize: '14px', fontWeight: '700', textDecoration: 'none', display: 'inline-flex', alignItems: 'center' },
}